version: '3'

services:
  database:
    container_name: database
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: mongod --quiet --logpath /dev/null 

  server:
    container_name: server
    build: ./server
    volumes:
      - ./server:/usr/app/server
    environment:
      - SECRET=${SECRET}
      - SERVER_PORT=${SERVER_PORT}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - database
  # client:
  #   container_name: client
  #   build: ./client
  #   volumes:
  #     - ./client/src:/usr/app/src
  #     - ./client/public:/usr/app/public
  #   ports:
  #     - 3000:3000
