version: '3'

services:
  database:
    container_name: database
    image: mongo
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null

  server:
    container_name: server
    build: ./server
    volumes:
      - ./server/src:/usr/app/server/src
    env_file:
      - .env
    ports:
      - 5000:5000

  client:
    container_name: client
    build: ./client
    environment:
      - SENTRY_CLIENT_DSN=${SENTRY_CLIENT_DSN}
    volumes:
      - ./client/src:/usr/app/client/src
      - ./client/public:/usr/app/client/public
    ports:
      - 3000:3000
    links:
      - server
    depends_on:
      - server
