export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_USER = 'GET_USER';
export const USER_ERROR = 'USER_ERROR';

export const GET_WORKSPACES = 'GET_WORKSPACES';
export const FILTER_WORKSPACES = 'FILTER_WORKSPACES';
export const WORKSPACES_ERROR = 'WORKSPACES_ERROR';

export const GET_BOOKINGS = 'GET_BOOKINGS';
export const POST_BOOKINGS = 'POST_BOOKINGS';
export const BOOKINGS_ERROR = 'BOOKINGS_ERROR';
