name: Create Release

on:
  push:
    branches: ['main']

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['client', 'server']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install ${{ matrix.directory}} dependencies
        run: yarn
        working-directory: ${{ matrix.directory }}

      - name: Run Lint
        run: yarn lint
        working-directory: ${{ matrix.directory }}

  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn --ignore-scripts

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  update_develop:
    name: Update develop Branch
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
      - name: Checkout develop Branch
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Git Config
        run: |
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git config user.name "${{ secrets.GIT_USERNAME }}"
      - name: Merge main Branch into develop (Rebase)
        run: git rebase origin/main
      - name: Push develop Branch
        run: git push

  deploy_production_env:
    name: Deploy Production Environment
    runs-on: ubuntu-latest
    needs: update_develop
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Staging Environment
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_APP_NAME}}
        env:
          HD_ADMIN_MAIL: ${{ secrets.ADMIN_MAIL }}
          HD_ADMIN_PWD: ${{ secrets.ADMIN_PWD }}
          HD_ADMIN_USER: ${{ secrets.ADMIN_USER }}
          HD_DB_URI: ${{ secrets.DB_URI }}
          HD_SECRET: ${{ secrets.SECRET}}
          HD_SERVER_PORT: ${{ secrets.SERVER_PORT }}
   
