name: Create Staging Environment

on:
  pull_request:
    branches: ['main']

jobs:
  # eslint:
  #   name: ESLint
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       directory: ['client', 'server']
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2

  #     - name: Install ${{ matrix.directory}} dependencies
  #       run: yarn
  #       working-directory: ${{ matrix.directory }}

  #     - name: Run Lint
  #       run: yarn lint
  #       working-directory: ${{ matrix.directory }}

  create_stating_env:
    # if: ${{ contains(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    # needs: eslint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Staging Environment
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: dev-${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_APP_NAME}}
        env:
          HD_ADMIN_MAIL: ${{ secrets.ADMIN_MAIL}}
          HD_ADMIN_PWD: ${{ secrets.ADMIN_PWD}}
          HD_ADMIN_USER: ${{ secrets.ADMIN_USER}}
          HD_DB_URI: ${{ secrets.DB_URI}}
          HD_SECRET: ${{ secrets.SECRET}}
          HD_SERVER_PORT: ${{ secrets.SERVER_PORT}}

  create_comment:
    runs-on: ubuntu-latest
    needs: create_stating_env
    steps:
      - name: Add Comment to Pull Request
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: 'For the Staging Environment visit http://dev-${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/'
          check_for_duplicate_msg: true
