name: Create Staging Environment

on:
  pull_request:
    branches: ['release/**']

jobs:
  bump_version:
    if: ${{ contains(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}
        run: npx semantic-release --plugins ['@semantic-release/commit-analyzer', '@semantic-release/npm', "@semantic-release/changelog"]

      - name: Show Changes
        run: |
          cat package.json
          cat CHANGELOG.md

      
        

      