name: Create Staging Environment

on:
  pull_request:
    branches: ['main']

jobs:
  bump_version:
    # if: ${{ contains(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: npx semantic-release

      - name: Show Changes
        run: |
          cat package.json
          cat CHANGELOG.md

      - name: Add Comment to Pull Request
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "For the Staging Environment visit http://dev-${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/"
          check_for_duplicate_msg: true