name: Test Project

on:
  push:
    branches-ignore: ['main']
  pull_request:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['client', 'server']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install ${{ matrix.directory}} dependencies
        run: npm install
        working-directory: ${{ matrix.directory }}

      - name: Run Lint
        run: npm run lint
        working-directory: ${{ matrix.directory }}

  codeql:
    name: Analyze Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'javascript'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1